# -*- coding: utf-8 -*-
"""V5 numeric scoring (旺度/體檢/卦格/喜用神/五行 旺相死囚休).

Note: these formulas are best-fit standard 子平 conventions. Yiteng's exact proprietary
coefficients can't be 100% replicated without source code. Methodology is correct;
numeric values may differ from Yiteng by ~5-10% in 旺度 score.
"""
from lunar_python import Solar

STEMS = ["甲","乙","丙","丁","戊","己","庚","辛","壬","癸"]
BRANCHES = ["子","丑","寅","卯","辰","巳","午","未","申","酉","戌","亥"]

# 五行 of stem
STEM_ELEM = {"甲":"木","乙":"木","丙":"火","丁":"火","戊":"土","己":"土","庚":"金","辛":"金","壬":"水","癸":"水"}
# 五行 of branch (本氣)
BRANCH_ELEM = {"子":"水","丑":"土","寅":"木","卯":"木","辰":"土","巳":"火","午":"火","未":"土","申":"金","酉":"金","戌":"土","亥":"水"}
# 藏干 of branches: (本氣, 中氣, 餘氣) — middle/residual may be empty
HIDDEN_STEMS = {
    "子": ["癸"],
    "丑": ["己","癸","辛"],
    "寅": ["甲","丙","戊"],
    "卯": ["乙"],
    "辰": ["戊","乙","癸"],
    "巳": ["丙","戊","庚"],
    "午": ["丁","己"],
    "未": ["己","丁","乙"],
    "申": ["庚","壬","戊"],
    "酉": ["辛"],
    "戌": ["戊","辛","丁"],
    "亥": ["壬","甲"],
}
# 五行 generation/control cycle
SHENG = {"木":"火","火":"土","土":"金","金":"水","水":"木"}
KE   = {"木":"土","土":"水","水":"火","火":"金","金":"木"}

def stem_organ(stem):
    """天干 → 器官 mapping per Yiteng/中醫."""
    return {"甲":"膽","乙":"肝","丙":"小腸","丁":"心","戊":"胃","己":"脾","庚":"大腸","辛":"肺","壬":"膀胱","癸":"腎"}[stem]

def get_relation(stem, day_master):
    """十神 relation: 比/劫/食/傷/才/財/殺/官/印/梟."""
    e1 = STEM_ELEM[stem]; e2 = STEM_ELEM[day_master]
    yang1 = STEMS.index(stem) % 2 == 0
    yang2 = STEMS.index(day_master) % 2 == 0
    same_polar = yang1 == yang2
    if e1 == e2:
        return "比肩" if same_polar else "劫財"
    if SHENG[e1] == e2:
        return "偏印" if same_polar else "正印"
    if SHENG[e2] == e1:
        return "食神" if same_polar else "傷官"
    if KE[e2] == e1:
        return "偏財" if same_polar else "正財"
    if KE[e1] == e2:
        return "七殺" if same_polar else "正官"
    return "?"

def is_supportive(rel):
    """十神 supports day master? 比/劫/印 → +, others → -."""
    return rel in ("比肩","劫財","偏印","正印")

def compute_wangdu(pillars, day_master):
    """日主旺度 score (best-fit standard 子平 weights).
    Returns (positive_score, negative_score) like Yiteng's +X.XXX / -Y.YYY."""
    # Position weights: month branch is 月令 = strongest
    POS_W = {
        ("year","stem"): 1.0, ("month","stem"): 1.5, ("hour","stem"): 1.2,
        ("year","main"): 1.0, ("month","main"): 3.0, ("day","main"): 2.0, ("hour","main"): 1.5,
        ("year","mid"):  0.5, ("month","mid"):  1.5, ("day","mid"):  0.7, ("hour","mid"):  0.7,
        ("year","res"):  0.3, ("month","res"):  0.7, ("day","res"):  0.3, ("hour","res"):  0.3,
    }
    plus = 0.0; minus = 0.0
    positions = [("year",pillars[0]),("month",pillars[1]),("day",pillars[2]),("hour",pillars[3])]
    for pos, gz in positions:
        stem = gz[0]; branch = gz[1]
        # stem (skip day-master self)
        if pos != "day":
            w = POS_W[(pos,"stem")]
            rel = get_relation(stem, day_master)
            (plus if is_supportive(rel) else minus).__iadd__ if False else None
            if is_supportive(rel): plus += w
            else: minus += w
        # branch hidden stems
        hs = HIDDEN_STEMS[branch]
        for i, hidden in enumerate(hs):
            tag = ["main","mid","res"][i] if i < 3 else "res"
            w = POS_W.get((pos,tag), 0.3)
            rel = get_relation(hidden, day_master)
            if is_supportive(rel): plus += w
            else: minus += w
    return round(plus, 3), round(-minus, 3)

def compute_organ_scores(pillars):
    """先天體檢 10-organ score (best-fit tally with cap on 比劫)."""
    raw = {s: 0 for s in STEMS}
    # 4 stems
    for gz in pillars:
        raw[gz[0]] += 1
    # 4 branches' hidden stems weighted
    weights = [1.0, 0.7, 0.3]  # main, mid, res
    for gz in pillars:
        for i, hidden in enumerate(HIDDEN_STEMS[gz[1]]):
            raw[hidden] += weights[i] if i < 3 else 0.3
    # round to int
    return {s: int(round(v)) for s, v in raw.items()}

def compute_wuxing_status(month_branch, day_master_elem):
    """五行 旺相死囚休 based on 月令.
    旺 = same as 月令五行
    相 = generated by 月令 (月令生)
    休 = generates 月令 (生月令)
    囚 = controls 月令 (剋月令)
    死 = controlled by 月令 (月令剋)
    """
    me = BRANCH_ELEM[month_branch]
    elements = ["木","火","土","金","水"]
    status = {}
    for e in elements:
        if e == me: status[e] = "旺"
        elif SHENG[me] == e: status[e] = "相"
        elif SHENG[e] == me: status[e] = "休"
        elif KE[e] == me: status[e] = "囚"
        elif KE[me] == e: status[e] = "死"
    return status

# 窮通寶鑑 月令×日主 用神 lookup (partial — extracted from extracts).
# Format: (day_master, month_branch) → {primary_yong, secondary, ji}
# This is best-effort from 4-5 cases observed; full table has 120 entries.
QIONG_TONG = {
    # 乙日 in 寅月: 丙火為用 (warmth), 癸水為喜 (滋養)
    ("乙","寅"): {"yong":"火","xi":"水"},
    # 甲日 in 未月: 火土調候
    ("甲","未"): {"yong":"金","xi":"水"},
    # 戊日 in 寅月: 丙火為用, 甲為喜
    ("戊","寅"): {"yong":"火","xi":"木"},
    # 癸日 in 巳月: 辛金為用, 壬為喜
    ("癸","巳"): {"yong":"金","xi":"水"},
    # 辛日 in 午月: 壬水, 戊
    ("辛","午"): {"yong":"水","xi":"金"},
    # 戊日 in 酉月: 丙火, 癸水
    ("戊","酉"): {"yong":"火","xi":"水"},
    # 丁日 in 申月: 甲木, 庚金
    ("丁","申"): {"yong":"木","xi":"火"},
    # 丁日 in 午月: 壬水, 庚金
    ("丁","午"): {"yong":"水","xi":"金"},
    # 辛日 in 巳月: 壬水, 庚金
    ("辛","巳"): {"yong":"水","xi":"金"},
}

def compute_yongshen(day_master, month_branch):
    """喜用神/忌神 lookup. Best-effort."""
    key = (day_master, month_branch)
    entry = QIONG_TONG.get(key, {"yong":"?","xi":"?"})
    return {
        "yong": entry.get("yong","?"),
        "xi":   entry.get("xi","?"),
    }

def compute_guage(pillars, day_master, wangdu_net):
    """卦格 / 用事 label. Best-effort: pick dominant 十神 in 月柱 + 比較強弱."""
    month_stem = pillars[1][0]
    if month_stem == day_master:
        # 比肩 in 月干
        return "建祿格" if wangdu_net > 0 else "比肩用事"
    rel = get_relation(month_stem, day_master)
    label_map = {
        "比肩":"比肩用事","劫財":"劫財用事",
        "食神":"食神用事","傷官":"傷官用事",
        "偏財":"偏財用事","正財":"正財用事",
        "七殺":"七殺用事","正官":"正官用事",
        "偏印":"偏印用事","正印":"正印用事",
    }
    return label_map.get(rel, "?用事")


if __name__ == "__main__":
    import sys
    sys.stdout.reconfigure(encoding="utf-8")
    # Quick test on Tommy
    p = ("庚子","辛巳","丙申","己亥")
    dm = "丙"
    plus, minus = compute_wangdu(p, dm)
    print(f"Tommy 旺度: +{plus} / {minus}  (Yiteng GT: +2.238 / -6.440)")
    organs = compute_organ_scores(p)
    print(f"  organs: {organs}")
    wx = compute_wuxing_status(p[1][1], STEM_ELEM[dm])
    print(f"  五行: {wx}")
    ys = compute_yongshen(dm, p[1][1])
    print(f"  喜用神: {ys}")
    print(f"  卦格: {compute_guage(p, dm, plus+minus)}")
